import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

export default function Home() {
	return (
		<>
			<Head>
				<title>UseEffect - Carousel</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className={styles.title}>Class 8: UseEffect-Carousel</h1>
			<main className={styles.main}>
				<Link href='/useEffectOne'> useEffectOne </Link>
				<Link href='/useEffectTwo'> useEffectTwo </Link>
				<Link href='/useEffectThree'> useEffectThree </Link>
				<Link href='/carouselPage'> Carousel Page </Link>
			</main>
		</>
	)
}